### ISSUE TITLE
APP crashed when WebDAV upload

### ISSUE THREAD

**Issue by iseki0** [Magisk-Modules-Repo/callrecorder-skvalex#14]
I press the "Add to WebDAV" item in the quick menu on record item. Then the APP crashed.

Logs:
```
10-07 17:27:07.074  3368  3454 W System.err: java.lang.NullPointerException: throw with null exception
10-07 17:27:07.074  3368  3454 W System.err:    at org.simpleframework.xml.core.ElementListLabel.getConverter(SourceFile:5)
10-07 17:27:07.075  3368  3454 W System.err:    at org.simpleframework.xml.core.CacheLabel.getConverter(Unknown Source:2)
10-07 17:27:07.075  3368  3454 W System.err:    at org.simpleframework.xml.core.c.e(SourceFile:3)
10-07 17:27:07.075  3368  3454 W System.err:    at org.simpleframework.xml.core.c.d(SourceFile:117)
10-07 17:27:07.075  3368  3454 W System.err:    at org.simpleframework.xml.core.c$a.a(SourceFile:44)
10-07 17:27:07.075  3368  3454 W System.err:    at org.simpleframework.xml.core.c.b(SourceFile:151)
10-07 17:27:07.075  3368  3454 W System.err:    at org.simpleframework.xml.core.k.h(SourceFile:33)
10-07 17:27:07.075  3368  3454 W System.err:    at org.simpleframework.xml.core.k.g(SourceFile:83)
10-07 17:27:07.075  3368  3454 W System.err:    at o.l11.handleResponse(SourceFile:23)
10-07 17:27:07.075  3368  3454 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:662)
10-07 17:27:07.076  3368  3454 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:632)
10-07 17:27:07.076  3368  3454 W System.err:    at o.kk1.c(SourceFile:5)
10-07 17:27:07.076  3368  3454 W System.err:    at o.kk1.d(SourceFile:45)
10-07 17:27:07.076  3368  3454 W System.err:    at o.d32.m(SourceFile:26)
10-07 17:27:07.077  3368  3454 W System.err:    at o.a32.g(SourceFile:31)
10-07 17:27:07.077  3368  3454 W System.err:    at o.z.run(SourceFile:30)
10-07 17:27:07.077  3368  3454 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-07 17:27:07.077  3368  3454 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-07 17:27:07.077  3368  3454 W System.err:    at java.lang.Thread.run(Thread.java:919)
10-07 17:27:07.105  3368  3454 E AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
10-07 17:27:07.105  3368  3454 E AndroidRuntime: Process: org.skvalex.cr, PID: 3368
10-07 17:27:07.105  3368  3454 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.skvalex.cr.cloud.sardine.model.Multistatus.getResponse()' on a null object reference
10-07 17:27:07.105  3368  3454 E AndroidRuntime:        at o.kk1.d(SourceFile:51)
10-07 17:27:07.105  3368  3454 E AndroidRuntime:        at o.d32.m(SourceFile:26)
10-07 17:27:07.105  3368  3454 E AndroidRuntime:        at o.a32.g(SourceFile:31)
10-07 17:27:07.105  3368  3454 E AndroidRuntime:        at o.z.run(SourceFile:30)
10-07 17:27:07.105  3368  3454 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-07 17:27:07.105  3368  3454 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-07 17:27:07.105  3368  3454 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
10-07 17:27:07.182  1672  1692 W ActivityTaskManager:   Force finishing activity org.skvalex.cr/.MainActivity
10-07 17:27:07.184  1672  3617 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
10-07 17:27:07.198  1672  1782 I ActivityManager: Showing crash dialog for package org.skvalex.cr u0
1
```

Version & Environment:

```
Version: 3.5.1
ROM: QQ2A.200405.005 PixelExperience_platina-10.0-20200408-0219-OFFICIAL
Android Version: 10
device product:platina model:MI_8_Lite device:platina transport_id:6
```

**Comment by skvalex** [comment]
this should be fixed in 3.5.2
